const envConfig = {
  public: {
    required: ['NEXT_PUBLIC_SITE_URL', 'NEXT_PUBLIC_TURNSTILE_SITE_KEY'],
    recommended: [
      'NEXT_PUBLIC_CONTACT_PHONE_FA',
      'NEXT_PUBLIC_CONTACT_PHONE_EN',
      'NEXT_PUBLIC_CONTACT_EMAIL',
      'NEXT_PUBLIC_GA_ID',
      'NEXT_PUBLIC_GTM_ID',
  ],
  },
  server: {
    required: [
      'CONTACT_PHONE_FA',
      'CONTACT_PHONE_EN',
      'CONTACT_EMAIL',
      'TURNSTILE_SECRET_KEY',
      'COMMENTS_ADMIN_TOKEN_SECRET',
    ],
    recommended: [
      'RESEND_API_KEY',
      'RESEND_FROM_EMAIL',
      'DATABASE_URL',
      'COMMENTS_DATABASE_URL',
      'RATE_LIMIT_REDIS_URL',
      'REDIS_URL',
      'COMMENTS_ADMIN_IDENTITIES',
      'COMMENTS_ADMIN_TOKEN',
      'COMMENTS_ADMIN_TOKEN_SECRETS',
      'COMMENTS_ADMIN_TOKEN_TTL_MINUTES',
      'COMMENTS_ADMIN_ID',
      'COMMENTS_ADMIN_NAME',
      'COMMENTS_ALLOWED_ORIGINS',
      'ALLOWED_ORIGINS',
      'COMMENTS_ALLOWED_PREVIEW_URLS',
      'ALLOWED_PREVIEW_ORIGINS',
    ],
  },
};

module.exports = envConfig;
